name: Build Windows App (.exe)

on:
  push:
    branches:
      - main
      - master
  workflow_dispatch: # Allows you to run this workflow manually from the Actions tab

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install dependencies
        working-directory: ./webapp
        run: npm install

      - name: Build Next.js
        working-directory: ./webapp
        env:
          SUPABASE_SERVICE_ROLE_KEY: dummy_key_to_pass_build
        run: npm run build:standalone

      - name: Build Electron (.exe)
        working-directory: ./webapp
        run: npm run dist

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: UPFEEDTH-Installer
          path: webapp/dist/*.exe
          retention-days: 7
